trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: playwright-variables # Contains Azure AD B2C credentials

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

# Install browsers with system dependencies for authentication
- script: |
    npx playwright install --with-deps chromium
  displayName: 'Install Chromium for auth setup'

- script: |
    npx playwright test tests/global.setup.js --project=setup --headed
  displayName: 'Run Authentication Setup'
  env:
    # Azure AD B2C credentials from variable group
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    # Extended timeouts for Azure AD B2C navigation
    PLAYWRIGHT_TIMEOUT: 120000
    PLAYWRIGHT_NAVIGATION_TIMEOUT: 60000

# Install remaining browsers after auth setup
- script: |
    npx playwright install firefox webkit msedge
  displayName: 'Install remaining browsers'

- script: |
    npx playwright test tests/features/auth/login/login.spec.js --project=chrome-unauthenticated
    npx playwright test tests/features/auth/login/login.spec.js --project=edge-unauthenticated
    npx playwright test tests/features/auth/login/login.spec.js --project=firefox-unauthenticated
    npx playwright test tests/features/auth/login/login.spec.js --project=webkit-unauthenticated
  displayName: 'Run Login Tests'
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)

- script: |
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=chrome-authenticated
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=edge-authenticated
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=firefox-authenticated
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=webkit-authenticated
  displayName: 'Run Dashboard Tests'
  env:
    TEST_USERNAME: $(AZURE_AD_B2C_USERNAME)
    TEST_PASSWORD: $(AZURE_AD_B2C_PASSWORD)

- task: PublishTestResults@2
  condition: always()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test-results/junit-report.xml'
    testRunTitle: 'Playwright Tests'
    testRunSystem: 'Azure Pipelines'
    buildConfiguration: 'Playwright'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Report'
