trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: playwright-variables # Contains Azure AD B2C credentials
  - name: authSucceeded
    value: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

# Install browsers with system dependencies for authentication
- script: |
    npx playwright install --with-deps chromium
  displayName: 'Install Chromium for auth setup'

# Run authentication setup with improved debugging and parameters
- script: |
    npx playwright test tests/global.setup.js --project=setup --headed --timeout=180000
    if exist auth.json (
      echo "##vso[task.setvariable variable=authSucceeded]true"
    )
  displayName: 'Run Authentication Setup'
  env:
    # Azure AD B2C credentials from variable group
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    # Extended timeouts for Azure AD B2C navigation
    PLAYWRIGHT_TIMEOUT: 180000
    PLAYWRIGHT_NAVIGATION_TIMEOUT: 120000
    # Flag to indicate running in pipeline
    CI: 'true'
    # Debug logging
    DEBUG: 'pw:api'

# Capture and publish auth artifacts even if auth fails
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/*.png'
    artifact: 'auth-debug-screenshots'
    publishLocation: 'pipeline'
  displayName: 'Publish Auth Debug Screenshots'
  continueOnError: true

# Install remaining browsers after auth setup
- script: |
    npx playwright install firefox webkit msedge
  displayName: 'Install remaining browsers'
  condition: succeeded()

# Run tests with better error handling and sequential execution
- script: |
    npx playwright test tests/features/auth/login/login.spec.js --project=chrome-unauthenticated
  displayName: 'Run Chrome Login Tests'
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/auth/login/login.spec.js --project=edge-unauthenticated
  displayName: 'Run Edge Login Tests'
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/auth/login/login.spec.js --project=firefox-unauthenticated
  displayName: 'Run Firefox Login Tests'
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/auth/login/login.spec.js --project=webkit-unauthenticated
  displayName: 'Run WebKit Login Tests'
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

# Only run authenticated tests if auth setup succeeded
- script: |
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=chrome-authenticated
  displayName: 'Run Chrome Dashboard Tests'
  condition: and(succeeded(), eq(variables.authSucceeded, 'true'))
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=edge-authenticated
  displayName: 'Run Edge Dashboard Tests'
  condition: and(succeeded(), eq(variables.authSucceeded, 'true'))
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=firefox-authenticated
  displayName: 'Run Firefox Dashboard Tests'
  condition: and(succeeded(), eq(variables.authSucceeded, 'true'))
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

- script: |
    npx playwright test tests/features/dashboard/navigate/dashboard.spec.js --project=webkit-authenticated
  displayName: 'Run WebKit Dashboard Tests'
  condition: and(succeeded(), eq(variables.authSucceeded, 'true'))
  env:
    AZURE_AD_B2C_USERNAME: $(AZURE_AD_B2C_USERNAME)
    AZURE_AD_B2C_PASSWORD: $(AZURE_AD_B2C_PASSWORD)
    CI: 'true'
  continueOnError: true

# Generate and publish test reports
- script: |
    npx playwright merge-reports --reporter=junit,html ./test-results
  displayName: 'Merge Test Reports'
  condition: always()
  continueOnError: true

- task: PublishTestResults@2
  condition: always()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test-results/junit-report.xml'
    testRunTitle: 'Playwright Tests'
    testRunSystem: 'Azure Pipelines'
    buildConfiguration: 'Playwright'
    mergeTestResults: true
    failTaskOnFailedTests: false
  displayName: 'Publish Test Results'
  continueOnError: true

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Report'
  continueOnError: true

# Publish all screenshots for debugging
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/**/*.png'
    artifact: 'test-screenshots'
    publishLocation: 'pipeline'
  displayName: 'Publish Test Screenshots'
  continueOnError: true