trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: playwright-variables # Contains Azure AD B2C credentials

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npx playwright install --with-deps
  displayName: 'Install dependencies and browsers'

- script: |
    npx playwright test tests/global.setup.js --project=setup
  displayName: 'Run Authentication Setup'
  env:
    TEST_USERNAME: $(AZURE_AD_B2C_USERNAME)
    TEST_PASSWORD: $(AZURE_AD_B2C_PASSWORD)

- script: |
    npx playwright test
  displayName: 'Run Playwright Tests'
  env:
    TEST_USERNAME: $(AZURE_AD_B2C_USERNAME)
    TEST_PASSWORD: $(AZURE_AD_B2C_PASSWORD)

- task: PublishTestResults@2
  condition: always()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test-results/junit-report.xml'
    testRunTitle: 'Playwright Tests'
    testRunSystem: 'Azure Pipelines'
    buildConfiguration: 'Playwright'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Report'
